name: 'Allure Report with history'
description: 'Generate Allure Report with history'
author: 'simple-elf'
branding:
  icon: 'layout'
  color: 'green'
inputs:
  allure_results:
    description: 'Allure test result data dir'
    required: true
    default: 'allure-results'
  allure_report:
    description: 'Allure report target dir'
    required: true
    default: 'allure-report'
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: true
    default: 'gh-pages'
  allure_history:
    description: 'Folder for allure history'
    required: true
    default: 'allure-history'
  subfolder:
    description: 'subfolder'
    required: false
    default: ''
  keep_reports:
    description: 'Keep X last reports'
    required: false
    default: '20'
  github_run_num:
    description: 'GitHub Actions build number'
    required: true
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: true
    default: ${{ github.run_id }}
  github_repo:
    description: 'GitHub repository'
    required: true
    default: ${{ github.repository }}
  github_repo_owner:
    description: 'GitHub repository owner'
    required: true
    default: ${{ github.repository_owner }}
  github_tests_repo:
    description: 'GitHub repository where test are run'
    required: true
    default: ${{ github.repository }}
  report_url:
    description: 'Use a custom URL instead of *.github.io'
    required: false
    default: ''
  github_server_url:
    description: 'GitHub server URL'
    required: true
    default: ${{ github.server_url }}
runs:
  using: 'composite'
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Cache Allure CLI
      uses: actions/cache@v3
      with:
        path: allure-cli
        key: allure-2.32.0

    - name: Download Allure if not cached
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -LO https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.32.0/allure-commandline-2.32.0.zip
        unzip allure-commandline-2.32.0.zip
        mv allure-2.32.0 allure-cli
        rm allure-commandline-2.32.0.zip
        chmod -R +x allure-cli/bin

    - name: Add Allure to PATH
      shell: bash
      run: echo "${{ github.workspace }}/allure-cli/bin" >> $GITHUB_PATH

    - name: Run entrypoint script
      run: bash "${{ github.action_path }}/entrypoint.sh"
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        INPUT_GH_PAGES: ${{ inputs.gh_pages }}
        INPUT_ALLURE_HISTORY: ${{ inputs.allure_history }}
        INPUT_GITHUB_REPO: ${{ inputs.github_repo }}
        INPUT_GITHUB_REPO_OWNER: ${{ inputs.github_repo_owner }}
        INPUT_SUBFOLDER: ${{ inputs.subfolder }}
        INPUT_REPORT_URL: ${{ inputs.report_url }}
        INPUT_KEEP_REPORTS: ${{ inputs.keep_reports }}
        INPUT_GITHUB_RUN_NUM: ${{ inputs.github_run_num }}
        INPUT_GITHUB_RUN_ID: ${{ inputs.github_run_id }}
        INPUT_GITHUB_SERVER_URL: ${{ inputs.github_server_url }}
        INPUT_GITHUB_TESTS_REPO: ${{ inputs.github_tests_repo }}
        INPUT_ALLURE_RESULTS: ${{ inputs.allure_results }}
        INPUT_ALLURE_REPORT: ${{ inputs.allure_report }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
