# .github/workflows/retrieve-and-print-info.yml
name: Retrieve and Print Info

on:
  workflow_run:
    workflows: ["Generate Zip File"]
    types:
      - completed

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: test-and-produce-zip.yml
          workflow_search: false
          workflow_conclusion: ""
          event: push
          name: result
          repo: ${{ github.repository }}
          check_artifacts: false
          search_artifacts: false
          skip_unpack: false
          if_no_artifact_found: fail
          allow_forks: true

      - name: Unzip the file
        run: |
          unzip result.zip -d extracted_files

      - name: Print info.txt
        run: |
          cat extracted_files/info.txt
