name: Run tests and trigger publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV_KIND: aba

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew clean test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: results-${{ env.ENV_KIND }}-${{ github.run_number }}
          path: build/allure-results

      - name: Trigger publish workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish.yml/dispatches \
          -d '{"ref":"main","inputs":{"env_kind":"${{ env.ENV_KIND }}","run_number":"${{ github.run_number }}"}}'

      - name: Add link to job summary
        run: echo "[Report](https://arturmkr.github.io/allure_report/${{ env.ENV_KIND }}/${{ github.run_number }}/)" >> $GITHUB_STEP_SUMMARY