name: Run tests and publish report
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew clean test

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results
          subfolder: aba

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate directory listing HTML
        if: always()
        run: |
          echo "<html><body><h1>Directory Listing</h1><ul>" > gh-pages/aba/list.html
          for dir in $(find gh-pages/aba -mindepth 1 -maxdepth 1 -type d | grep -v "last-history"); do
            dirname=$(basename $dir)
            echo "<li><a href=\"$dirname\">$dirname</a></li>" >> gh-pages/aba/list.html
          done
          echo "</ul></body></html>" >> gh-pages/aba/list.html

      - name: Publish updated directory listing
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages